---
- name: Install keepalived.
  yum: name=keepalived state=present

- name: Copy check nfs health script
  copy: src=./script/check_nfs_health.sh dest=/home/script owner={{ user }} mode=755

#- name: Copy keepalive script
#  template: src=check_nfs_health.sh dest=/home/script/

# - name: Set Java Home Script
#  shell: source /etc/profile.d/java_home.sh
